### PR TITLE
Perform CI over Erlang 24

### PR DESCRIPTION
**Pull request by paulo-ferraz-oliveira**

### CODE REVIEW

**Comment by g-andrade** [comment]
Should this change accompany the bump to `minimum_otp_vsn` or do you intend on doing that separately?

**Comment by paulo-ferraz-oliveira** [comment]
I prefer to separate it. The goal, with this pull request, is to broaden the CI scope, not shift it. Also, moving minimum might/should (?) be done with other lib.s at the same time, but I don't manage that strategy any more.

**Review by g-andrade — APPROVED** [review]

**Comment by g-andrade** [comment]
[CI failed](https://github.com/miniclip/poolgirl/runs/2773481320?check_suite_focus=true). I'm going to assume it's gamma ray bit-flip silly season and ignore it, since the error message is entirely unreasonable (OTP version 23 was unavailable.)

**Comment by paulo-ferraz-oliveira** [comment]
> [CI failed](https://github.com/miniclip/poolgirl/runs/2773481320?check_suite_focus=true). I'm going to assume it's gamma ray bit-flip silly season and ignore it, since the error message is entirely unreasonable (OTP version 23 was unavailable.)

It's not unreasonable, but it is wrong. Since Fast.ly was down, Hex.pm (the source for `setup-beam` Erlang) was also down. This got, unfortunately, wrongly translated into the error message you might have witnessed. Going to re-run the CI to see if there's actually any errors (there weren't before, though).

**Comment by paulo-ferraz-oliveira** [comment]
CI's good: https://github.com/miniclip/poolgirl/actions/runs/918169821.

**Pull request merged**
